### ISSUE TITLE
Keyify header names

### ISSUE THREAD

**Issue by metasoarous** [metasoarous/semantic-csv#1]
As pointed out in the README, would be nice to write `(:more row)` as apposed to `(get row "more")`.

**Comment by ship561** [comment]
This should also take care of spaces in header names otherwise only the first word in a particular column header is keyified leading to mapify not working. Certainly combining spaces can be taken care of in many different ways. Here, I replace spaces with "." because I'm somewhat used to R, but obviously anything will do here (likely "-" since its Clojure).

``` 
(let [f (csv/read-csv rdr)]
 (map #(clojure.string/replace % #" " ".") (first f)))
```

**Comment by metasoarous** [comment]
Hi @ship561.

Actually, you can have a keyword with spaces in it. They're just not as fun to use.

As you can see in #26, we're working on a `:transform-header` option that lets you pass in your own function for casting header names as you wish. The default (simply `keyify`) will remain as is for the next release or two, but once we bump to 1.0, we'll make the default for `:keyify true` be to downcase, split by spaces, join with `"-"`, and then apply `keyword`. But you'll be able to pass whatever casting function you like via `:transform-header`. If I hear a call for more flexible casting function helpers for casting headers, I may consider adding things that would let you customize what you replace spaces with and the like. But it's not hard to write these things, and I don't want to clutter the API if not many people will be using it.
