### ISSUE TITLE
Do you accept other separators than , ?

### ISSUE THREAD

**Issue by endrebak** [metasoarous/semantic-csv#40]
Could not find it in the docs.

I am a complete clj-newb, otherwise I would have made a PR.

I guess I could use the regular csv-reader and mappify, but would love the slurpers and spitters to accept different (input/output) separators.

(The divine (python) pandas library even accepts all regexes as separators - like `\s+` to read both spaces and tabs as a separator, but that might be hard to implement here, dunno...)

**Comment by metasoarous** [comment]
See the docs for `parse-and-process`. You can use the `:parser-opts` option to specify options to pass to the `clojure-csv/parse-csv` function. This is also true of `slurp-csv`. Similarly with `:writer-opts` on `spit-csv`. I don't know for sure that `clojure-csv` lets you use regular expressions, but there's a good chance it does. If not, that's something I might make a switch for as far as the underlying implementation. (To be clear, as indicated in the docs, semantic-csv focuses on dealing with the *semantics* of csv data, leaving the more syntactic concern of translating CSV text into some sequence of rows a separate concern, since there are already Clojure tools for the latter purpose; So really you can do whatever you like with semantic CSV, including implement your own translation function.)
